name: Auto
on:
#   pull_request:
#     types:
#     - closed
#     branches:
#     - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Get Version Tag
          id: version
          uses: paulhatch/semantic-version@v5.0.2
          with:
            tag_prefix: ''
            major_pattern: "Major"
            minor_pattern: "Minor"
            version_format: "${major}.${minor}.${patch}-prerelease${increment}"
            change_path: ""
            # search_commit_body: true
            # If this is set to true, *every* commit will be treated as a new version.
            bump_each_commit: true
        - name: Create Release
          uses: ncipollo/release-action@v1
          with:
            tag: ${{ steps.version.outputs.version_tag }}
            name: Version ${{ steps.version.outputs.version_tag }}
            generateReleaseNotes: true
            # draft: true
            # prerelease: true
            makeLatest: true
            updateOnlyUnreleased: false
            allowUpdates: true
            omitBodyDuringUpdate: true
            omitNameDuringUpdate: true
            omitPrereleaseDuringUpdate: true